---
postgresql_version: "16"
postgresql_listen_addresses: "*"
postgresql_data_directory: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_max_connections: 100
postgresql_register_consul: true

postgresql_apt_list:
  - "postgresql-{{ postgresql_version }}"
  - "postgresql-client-{{ postgresql_version }}"
  - python3-psycopg2

postgresql_pip_list:
  - psycopg2-binary
