---
docker_arch: "{{ arch_map[ansible_facts['architecture']] | default(ansible_facts['architecture']) }}"
docker_apt_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
