---
- name: Install Multipass via Homebrew
  community.general.homebrew_cask:
    name: "{{ multipass_package }}"
    state: present
  become: false

- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ role_path }}/files"
    state: directory
    mode: "0755"

- name: Create cloud-init file
  ansible.builtin.template:
    src: 'cloud-init.yml.j2'
    dest: "{{ role_path }}/files/cloud-init.yml"
    mode: '0644'
  vars:
    ssh_key: >
      "{{ lookup('ansible.builtin.file', '~/.ssh/id_ed25519.pub') }}"
  changed_when: false
