---
- name: Check if multipass is installed
  ansible.builtin.command: "{{ homebrew_bin_path }} list --cask multipass"
  register: multipass_check
  ignore_errors: true
  changed_when: false

- name: Set fact for multipass_installed
  ansible.builtin.set_fact:
    multipass_installed: "{{ multipass_check.rc == 0 }}"

- name: Debug state decision
  ansible.builtin.debug:
    msg:
      - "Multipass installed: {{ multipass_installed }}"
      - "hypervisors.multipass: {{ hypervisors.multipass | default('undefined') }}"

- name: Include uninstall tasks
  ansible.builtin.include_tasks: uninstall.yml
  when: multipass_installed and not hypervisors.multipass | default(false)

- name: When multipass is True
  when: hypervisors.multipass | default(false)
  block:
    - name: Include install tasks
      ansible.builtin.include_tasks: install.yml
      when: not multipass_installed

    - name: Include update tasks
      ansible.builtin.include_tasks: update.yml
      when: multipass_installed

    - name: Manage VMs
      ansible.builtin.include_tasks: manage.yml
