---
- name: Create vm_list variable dynamically
  ansible.builtin.set_fact:
    vm_list: "{{ inventory_hostname }}_{{ nodes | join('_') }}_vms"

- name: Debug vm_list variable
  ansible.builtin.debug:
    msg: "Generated vm_list name: {{ vm_list }}"

- name: Show all hosts in the dynamically generated vm_list group
  ansible.builtin.debug:
    msg: "Hosts in {{ vm_list }}: {{ groups[vm_list] | default([]) }}"

- name: Debug remote PATH
  ansible.builtin.debug:
    var: ansible_env.PATH

- name: Check multipass list
  ibiscardigan.multipass.list:
  register: active_list

- name: Debug active_list
  ansible.builtin.debug:
    var: active_list

- name: Create a Multipass VMs
  ibiscardigan.multipass.hosts:
    name: "{{ item }}"
    image: "{{ hostvars[item]['image'] | default('lts') }}"
    cpus: "{{ hostvars[item]['cores'] | default(1) }}"
    memory: "{{ hostvars[item]['memory'] | default(1) }}G"
    disk: "{{ hostvars[item]['storage'] | default(4) }}G"
    cloud_init: "{{ role_path }}/files/cloud-init.yml"
    network: "{{ ansible_default_ipv4.device }}"
    state: present
  loop: "{{ groups[vm_list] }}"
  register: created_vms

- name: Inject ansible_host for each desired VM
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    ansible_host: "{{ item.value.ipv4[1] }}"
  loop: "{{ active_list.instances | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.key in groups[ vm_list ]

- name: Debug ansible_host for each VM in {{ vm_group }}
  ansible.builtin.debug:
    msg: "{{ item }} → {{ hostvars[item].ansible_host }}"
  loop: "{{ groups[inventory_hostname ~ '_' ~ (nodes | join('_')) ~ '_vms'] }}"
  loop_control:
    label: "{{ item }}"

- name: Compute running VMs to remove
  set_fact:
    unwanted_vms: >-
      {{ active_list.instances
         | dict2items
         | selectattr('value.state','equalto','Running')
         | map(attribute='key')
         | list
         | difference( groups[vm_list] )
      }}

- name: Debug unwanted_vms
  debug:
    var: unwanted_vms

- name: Delete running VMs not in desired list
  ibiscardigan.multipass.hosts:
    name: "{{ item }}"
    state: absent
  loop: "{{ unwanted_vms }}"
  when: unwanted_vms | length > 0
