# base_host_attributes
ansible_python_interpreter: /opt/homebrew/opt/python@3.13/bin/python3
pip_executable: null

# services
ai:
  llama_cpp: true
datastores:
  kafka: false
  mosquito_mqtt: false
  nfs: false
  postgres: false
  redis: false
  timescaledb: false
games:
  minecraft: false
home:
  firefly_iii: false
  frigate_nvr: false
  home_assistant: false
  homepage: false
  mosquito_mqtt: false
  nomad: false
hypervisors:
  multipass: true
  proxmox: false
management:
  docmost: false
  huly: false
network:
  keepalived: false
  nginx: false
  pihole: false
  unbound: false
observability:
  alertmanager: false
  grafana: false
  loki: false
  node_exporter: false
  promtail: false
  victoria_metrics: false
  vmagent: false
orchestration:
  ansible: false
  artifactory: false
  consul: false
  docker: false
  homebrew: true
  nomad: true
