---
- name: Unmount all NFS mounts
  ansible.builtin.shell: |
    awk '$3 == "nfs" { print $2 }' /proc/mounts | xargs -r umount -f
  args:
    executable: /bin/bash
  become: true
  changed_when: false

- name: Check if /mnt exists and is a directory
  ansible.builtin.stat:
    path: /mnt
  register: mnt_stat

- name: Remove all NFS mount directories
  ansible.builtin.find:
    paths: /mnt
    file_type: directory
    patterns: '*'
    recurse: no
  register: nfs_mount_dirs
  become: true
  when: mnt_stat.stat.exists and mnt_stat.stat.isdir

- name: Delete NFS mount directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ nfs_mount_dirs.files }}"
  become: true
  when: item.path is match('^/mnt/')

- name: Check if /etc/exports exists
  ansible.builtin.stat:
    path: /etc/exports
  register: exports_file

- name: Remove all NFS exports from /etc/exports
  ansible.builtin.blockinfile:
    path: /etc/exports
    block: ""
    marker: "# {mark} ANSIBLE MANAGED BLOCK - NFS EXPORTS"
    state: absent
  when: exports_file.stat.exists
  become: true

- name: Check if exportfs command is available
  ansible.builtin.command: which exportfs
  register: exportfs_check
  changed_when: false
  failed_when: false

- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  when: exportfs_check.rc == 0
  become: true
  changed_when: false

- name: Stop and disable NFS server if present
  ansible.builtin.systemd:
    name: nfs-server
    state: stopped
    enabled: false
  become: true
  when: ansible_facts.services['nfs-server.service'] is defined
