---
- name: Get list of active NFS exports
  ansible.builtin.command: exportfs -v
  register: nfs_exports
  changed_when: false
  become: true

- name: Validate expected NFS exports are present
  ansible.builtin.assert:
    that: "'{{ item.value.nfs_export_path }}' in nfs_exports.stdout"
    fail_msg: "Expected NFS export for {{ item.key }} not found"
    success_msg: "NFS export for {{ item.key }} verified"
  loop: "{{ nfs_paths[datastores.nfs] | dict2items }}"
