---
- name: Unregister Firefly job from Nomad
  ansible.builtin.command: >
    nomad job stop -purge firefly
  register: firefly_nomad_stop
  changed_when: "'purged' in firefly_nomad_stop.stdout"
  failed_when: false  # Job might not exist
  become: true

- name: Remove Firefly job HCL file
  ansible.builtin.file:
    path: "{{ nomad_job_dir }}/firefly.nomad"
    state: absent
  become: true

- name: Unmount Firefly NFS mount
  ansible.posix.mount:
    path: "{{ nfs_paths['home']['firefly_iii'].nfs_mount_path }}"
    state: unmounted
  become: true

- name: Remove Firefly NFS mount path
  ansible.builtin.file:
    path: "{{ nfs_paths['home']['firefly_iii'].nfs_mount_path }}"
    state: absent
  become: true
