---
- name: Restart NFS
  ansible.builtin.service:
    name: nfs-server
    state: restarted
    enabled: true
  become: true

- name: Validate NFS
  ansible.builtin.include_tasks: validate.yml
  listen: Validate NFS

- name: Reload Consul
  ansible.builtin.service:
    name: consul
    state: reloaded
  become: true
