---
- name: "Find all Postgres data directories under {{ postgres_data_root }}"
  ansible.builtin.find:
    paths: "{{ postgres_data_root }}"
    file_type: directory
    depth: 1
  register: postgres_data_dirs

- name: "Build list of expected mount paths"
  ansible.builtin.set_fact:
    expected_dirs: >-
      {{ (postgres_clusters_merged | default([]))
         | map(attribute='storage.mount_path')
         | list }}

- name: "Determine orphaned data directories"
  ansible.builtin.set_fact:
    orphaned_dirs: >-
      {{ postgres_data_dirs.files
         | map(attribute='path')
         | difference(expected_dirs) }}

- name: "Remove orphaned Postgres data directories"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
    recurse: yes
  loop: "{{ orphaned_dirs }}"
  when: orphaned_dirs is defined and orphaned_dirs | length > 0
