
---
- name: Ensure data directories for each Postgres cluster
  ansible.builtin.file:
    path: "{{ item.storage.mount_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ postgres_clusters_merged }}"
  become: true

- name: Ensure /etc/patroni exists
  ansible.builtin.file:
    path: /etc/patroni
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Render Patroni configuration for each cluster
  ansible.builtin.template:
    src: patroni.yml.j2
    dest: "/etc/patroni/patroni-{{ item.name }}.yml"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ postgres_clusters_merged }}"
  become: true

- name: Install python3-requests using apt
  ansible.builtin.apt:
    name: python3-requests
    state: present
  become: true
