---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd
  become: true

- name: Restart Consul
  ansible.builtin.systemd:
    name: "{{ consul_service }}"
    enabled: true
    state: restarted
  listen: Restart Consul
  become: true

- name: Validate Consul
  ansible.builtin.include_tasks: validate_server.yml
  when: consul_server | default(false)
  listen: Validate Consul

- name: Validate Consul (client)
  ansible.builtin.include_tasks: validate_client.yml
  when: not consul_server | default(true)
  listen: Validate Consul

- name: Restart systemd-resolved
  become: true
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
    enabled: true
