---
- name: Ensure registry data dir exists
  ansible.builtin.file:
    path: "{{ docker_registry_data_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Ensure registry config dir exists
  ansible.builtin.file:
    path: "{{ docker_registry_config_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Copy Docker registry config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ docker_registry_config_dir }}/config.yml"
    mode: '0644'
  become: true
