---
- name: Install Docker registry
  ansible.builtin.include_tasks: install.yml
  when:
    - meta_class == 'data'
    - meta_domain == 'infra'

- name: Run Nomad
  ansible.builtin.include_tasks: nomad.yml
  when:
    - meta_class == 'data'
    - meta_domain == 'infra'

- name: Manage Docker registry
  ansible.builtin.include_tasks: manage.yml
  when:
    - meta_class == 'data'
    - meta_domain == 'infra'
    - docker_registry_mirrors | length > 0
