---
- name: Check if image already exists in internal registry
  ansible.builtin.command:
    cmd: docker manifest inspect {{ item.target }}:{{ item.tag }}
  register: manifest_check
  failed_when: false
  changed_when: false
  loop: "{{ docker_registry_mirrors }}"

- name: Log in to GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: ibiscardigan
    password: "{{ github_packages_pat }}"
  become: true

- name: Mirror image if not already present
  ansible.builtin.include_tasks: mirror.yml
  loop: "{{ docker_registry_mirrors | zip(manifest_check.results) | list }}"
  loop_control:
    loop_var: mirror_pair
  when: mirror_pair.1.rc != 0
