---
- name: Render Nomad job file
  ansible.builtin.template:
    src: docker-registry.nomad.j2
    dest: "/opt/nomad/jobs/{{ docker_registry_job_name }}.nomad"
    mode: '0644'
  become: true

- name: Run Nomad job
  ansible.builtin.command:
    cmd: "nomad job run /opt/nomad/jobs/{{ docker_registry_job_name }}.nomad"
  changed_when: true
