---
- name: Sync time on Linux using systemd
  when:
    - ansible_facts['os_family'] == 'Debian' or ansible_facts['os_family'] == 'RedHat'
  block:
    - name: Check if NTP was previously enabled
      ansible.builtin.stat:
        path: /var/lib/ansible/.ntp_enabled
      register: ntp_marker

    - name: Try to enable NTP via timedatectl (first run only)
      ansible.builtin.command: timedatectl set-ntp true
      when: not ntp_marker.stat.exists
      register: enable_ntp
      ignore_errors: true
      changed_when: false

    - name: Create marker file if timedatectl succeeded
      ansible.builtin.file:
        path: /var/lib/ansible/.ntp_enabled
        state: touch
        mode: "0644"
      when: enable_ntp is succeeded

    - name: Install ntpdate if timedatectl failed
      ansible.builtin.apt:
        name: ntpdate
        state: present
        update_cache: true
      when: enable_ntp is failed
      become: true

    - name: Force time sync with ntpdate if timedatectl failed
      ansible.builtin.command: ntpdate time.cloudflare.com
      when: enable_ntp is failed
      register: ntpdate_sync
      changed_when: "'adjust time server' in ntpdate_sync.stdout"
      become: true

- name: Sync time on macOS
  ansible.builtin.command: sntp -sS time.apple.com
  when: ansible_facts['system'] == 'Darwin'
  become: true
