- name: Run master playbook
  hosts: "{{ nodes | default(['dev']) }}"
  gather_facts: false

- name: Run hypervisors.yml
  import_playbook: hypervisors.yml

- name: Run provision.yml
  import_playbook: provision.yml

- name: Run orchestration.yml
  import_playbook: orchestration.yml

- name: Run services.yml
  import_playbook: services.yml
