---
- name: Provision the base functionality on hosts
  hosts: "{{ target_hosts | default(nodes | default(['dev'])) }}"
  gather_facts: yes

  roles:
    - role: homebrew
      when: ansible_system == 'Darwin'

    - role: python
