---
- name: Provision the base functionality on hosts
  hosts: "{{ nodes | default(['dev']) }}"
  gather_facts: yes

  tasks:
    - name: Skip non‑macOS hosts
      ansible.builtin.meta:
        end_host: true
      when: ansible_facts['ansible_system'] != 'Darwin'

  roles:
    - homebrew
