---
- name: Dynamically group all hypervisor-enabled hosts
  hosts: all
  gather_facts: false

  tasks:
    - name: Group as "dynamic_hypervisors" if any hypervisor is true
      ansible.builtin.group_by:
        key: dynamic_hypervisors
      when: >
        (hostvars[inventory_hostname].hypervisors.multipass | default(false)) or
        (hostvars[inventory_hostname].hypervisors.proxmox | default(false))
      changed_when: false

- name: Filter dynamic hypervisors against nodes list
  hosts: dynamic_hypervisors
  gather_facts: false
  vars:
    resolved_nodes: >-
      {{
        nodes | default([]) | flatten
        | map('extract', groups)
        | select('defined')
        | flatten
        | union(
            nodes | default([]) | flatten
            | select('in', groups['all'])
          )
        | unique
      }}

  tasks:
    - name: Add host to final_hypervisors group if it matches resolved nodes
      ansible.builtin.group_by:
        key: final_hypervisors
      when: inventory_hostname in resolved_nodes
      changed_when: false

- name: Show dynamic groups and final target hosts
  hosts: localhost
  gather_facts: false
  vars:
    resolved_nodes: >-
      {{
        nodes | default([]) | flatten
        | map('extract', groups)
        | select('defined')
        | flatten
        | union(
            nodes | default([]) | flatten
            | select('in', groups['all'])
          )
        | unique
      }}

  tasks:
    - name: Show hosts in dynamic_hypervisors
      ansible.builtin.debug:
        var: groups['dynamic_hypervisors']

    - name: Show resolved nodes
      ansible.builtin.debug:
        var: resolved_nodes

    - name: Show final provision targets
      ansible.builtin.debug:
        var: groups['final_hypervisors']

- name: Provision the hypervisors and manage the VMs
  hosts: final_hypervisors
  gather_facts: true
  environment:
    PATH: "/usr/local/bin:/opt/homebrew/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Multipass remove hosts
      when: >
        hostvars[inventory_hostname].hypervisors is defined and
        hostvars[inventory_hostname].hypervisors.multipass | default(false) and
        ansible_system == 'Darwin'
      block:
        - name: Create vm_list variable dynamically
          ansible.builtin.set_fact:
            vm_list: "{{ inventory_hostname }}_{{ nodes | join('_') }}_vms"

        - name: Delete running VMs
          ibiscardigan.multipass.hosts:
            name: "{{ item }}"
            state: absent
          loop: "{{ groups[vm_list] }}"

        - name: Set host_vars_path dynamically
          ansible.builtin.set_fact:
            host_vars_path: "{{ playbook_dir }}/../host_vars"

        - name: Remove generated host_vars for all VMs
          ansible.builtin.file:
            path: "{{ host_vars_path }}/{{ item }}.yml"
            state: absent
          loop: "{{ groups[vm_list] }}"
          delegate_to: localhost

        - name: Clear known_hosts file on localhost
          ansible.builtin.file:
            path: "{{ lookup('env', 'HOME') }}/.ssh/known_hosts"
            state: absent
          delegate_to: localhost
          run_once: true

        - name: Clear all content from known_hosts
          ansible.builtin.copy:
            dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
            content: ""
            mode: '0600'
