---
- name: Provision the services on hosts
  hosts: "{{ target_hosts | default(nodes | default(['dev'])) }}"
  gather_facts: yes

  tasks:
    - name: Include n8n role conditionally
      ansible.builtin.include_role:
        name: n8n
      when:
        - ansible_system != 'Darwin'
        - meta_class == 'compute'
        - meta_domain == 'ai'
