- name: Debug Install
  ansible.builtin.debug:
    msg: "Installing Python on {{ ansible_architecture }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 7200
  when: ansible_system != 'Darwin'
  become: true

- name: Import Mac Install
  ansible.builtin.include_tasks: install_mac.yml
  when: ansible_system == 'Darwin'

- name: Import x86 Install
  ansible.builtin.include_tasks: install_x86.yml
  when:
    - ansible_architecture in ["aarch64", "x86_64"]
    - ansible_facts['os_family'] == "Debian"

- name: Debug computed ansible_python_interpreter
  ansible.builtin.debug:
    var: computed_python_interpreter

- name: Check if pip binary exists for computed interpreter
  ansible.builtin.stat:
    path: "{{ computed_python_interpreter | regex_replace('python(\\d+\\.?\\d*)$', 'pip\\1') }}"
  register: pip_executable_stat

- name: Set pip_executable fact (if found)
  ansible.builtin.set_fact:
    pip_executable: "{{ pip_executable_stat.stat.path }}"
  when: pip_executable_stat.stat.exists

- name: Read existing host_vars file (if present)
  ansible.builtin.slurp:
    src: "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}.yml"
  register: existing_host_vars
  ignore_errors: true
  delegate_to: localhost

- name: Decode and parse existing YAML (if any)
  ansible.builtin.set_fact:
    parsed_host_vars: "{{ existing_host_vars.content | b64decode | from_yaml }}"
  when: existing_host_vars is defined and existing_host_vars.content is defined
  delegate_to: localhost

- name: Merge python and pip vars into host_vars
  ansible.builtin.set_fact:
    merged_host_vars: >-
      {{
        (parsed_host_vars | default({}))
        | combine({
            'ansible_python_interpreter': computed_python_interpreter,
            'pip_executable': pip_executable
          })
      }}
  delegate_to: localhost

- name: Write merged host_vars to file
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}.yml"
    content: "{{ merged_host_vars | to_nice_yaml(indent=2) }}"
  delegate_to: localhost

- name: Refresh inventory to pick up modified host_vars
  meta: refresh_inventory

- name: Import deploy_packages
  ansible.builtin.include_tasks: deploy_packages.yml
  when: ansible_facts['os_family'] == "Debian"
