- name: Debug Install
  ansible.builtin.debug:
    msg: "Installing Python on {{ ansible_architecture }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 7200
  when: ansible_system != 'Darwin'
  become: true

- name: Import Mac Install
  ansible.builtin.include_tasks: install_mac.yml
  when: ansible_system == 'Darwin'

- name: Import x86 Install
  ansible.builtin.include_tasks: install_x86.yml
  when:
    - ansible_architecture in ["aarch64", "x86_64"]
    - ansible_facts['os_family'] == "Debian"

- name: Debug computed ansible_python_interpreter
  ansible.builtin.debug:
    var: computed_python_interpreter

- name: Check if pip binary exists for computed interpreter
  ansible.builtin.stat:
    path: "{{ computed_python_interpreter | regex_replace('python(\\d+\\.?\\d*)$', 'pip\\1') }}"
  register: pip_executable_stat

- name: Set pip_executable fact (if found)
  ansible.builtin.set_fact:
    pip_executable: "{{ pip_executable_stat.stat.path }}"
  when: pip_executable_stat.stat.exists

- name: Load existing host_vars for {{ inventory_hostname }}
  ansible.builtin.set_fact:
    existing_host_vars_raw: >-
      {{
        lookup(
          'file',
          playbook_dir ~ '/../host_vars/' ~ inventory_hostname ~ '.yml',
          errors='ignore'
        )
        | default('', true)
      }}
  delegate_to: localhost

- name: Parse raw YAML into dict
  ansible.builtin.set_fact:
    existing_host_vars: >-
      {{
        existing_host_vars_raw
        | from_yaml
        | default({}, true)
      }}
  delegate_to: localhost

- name: Merge interpreter + pip into that dict
  ansible.builtin.set_fact:
    updated_host_vars: >-
      {{
        existing_host_vars
        | combine({
            'ansible_python_interpreter': computed_python_interpreter,
            'pip_executable': pip_executable
          }, recursive=True)
      }}
  delegate_to: localhost

- name: Write back updated host_vars for {{ inventory_hostname }}
  ansible.builtin.copy:
    dest: "{{ playbook_dir }}/../host_vars/{{ inventory_hostname }}.yml"
    content: >-
      {{ updated_host_vars
         | to_nice_yaml(indent=2)
         | regex_replace('^---\n','') }}
    mode: '0644'
  delegate_to: localhost

- name: Refresh inventory to pick up new host_vars
  meta: refresh_inventory
