---
- name: Show interpreter
  ansible.builtin.debug:
    var: ansible_python_interpreter

- name: Show system
  ansible.builtin.debug:
    var: ansible_system

- name: Linux block
  when:
    - ansible_system != 'Darwin'
  block:
    - name: Ensure pip is installed
      ansible.builtin.apt:
        name:
          - python3-pip
        state: present
        update_cache: yes
      become: true
