---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
  become: true

- name: Reload Consul
  ansible.builtin.service:
    name: consul
    state: reloaded
  become: true

- name: Validate Postgres
  ansible.builtin.include_tasks: validate.yml
  listen: Validate Postgres
