# defaults/main.yml

# Image and version
firefly_iii_image: fireflyiii/core
firefly_iii_version: "latest"

# Nomad job parameters
firefly_iii_nomad_namespace: default
firefly_iii_nomad_region: global
firefly_iii_nomad_datacenters: ["{{ meta_datacentre }}"]
firefly_iii_nomad_job_name: "firefly-iii"
firefly_iii_nomad_group_name: "firefly"

# Network
firefly_iii_service_name: "firefly-iii"

# Storage
firefly_iii_storage_enabled: true
firefly_iii_storage_path: "/opt/firefly/uploads"
firefly_iii_storage_mount: "firefly_uploads"

# Environment variables (override in vault or inventory)
firefly_iii_env:
  APP_KEY: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
  APP_URL: "http://{{ inventory_hostname }}:{{ firefly_iii_host_port }}"
  DB_CONNECTION: "pgsql"
  DB_HOST: "postgres.service.consul"
  DB_PORT: "5432"
  DB_DATABASE: "firefly"
  DB_USERNAME: "firefly"
  DB_PASSWORD: "firefly_pass"
  TRUSTED_PROXIES: "**"
  LOG_CHANNEL: "stack"

# Consul service registration
firefly_iii_consul_tags:
  - "urlprefix-/firefly"

# Vault integration (optional)
firefly_iii_use_vault: false
firefly_iii_vault_path: "secret/firefly_iii"
