---
# Ensure the Nomad jobs directory exists
- name: Ensure Nomad jobs directory is present
  ansible.builtin.file:
    path: /etc/nomad/jobs
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure host data directory exists for n8n
  become: true
  ansible.builtin.file:
    path: "{{ n8n_nomad_volume.host_path }}"
    state: directory
    owner: 1000                   # UID of 'node' inside the n8n image
    group: 1000                   # GID of 'node' inside the n8n image
    mode: '0755'

- name: Ensure config subdirectory exists
  become: true
  ansible.builtin.file:
    path: "{{ n8n_nomad_volume.host_path }}/.n8n/config"
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

# Render the Nomad HCL template
- name: Render n8n Nomad job spec
  ansible.builtin.template:
    src: n8n.nomad.j2
    dest: /etc/nomad/jobs/{{ n8n_nomad_job_name }}.nomad
    owner: root
    group: root
    mode: '0644'

# Register or update the job in Nomad
- name: Register N8N job with Nomad
  ansible.builtin.command: >
    nomad job run /etc/nomad/jobs/{{ n8n_nomad_job_name }}.nomad
  register: n8n_nomad_job
  changed_when: "'Submitted job' in n8n_nomad_job.stdout"
  failed_when: n8n_nomad_job.rc != 0
  become: true
