---
- name: Ensure n8n data directory exists
  ansible.builtin.file:
    path: "{{ n8n_data_path }}/.n8n"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"
  become: true

- name: Register n8n Nomad job
  ansible.builtin.template:
    src: n8n.nomad.j2
    dest: /opt/nomad/jobs/{{ n8n_nomad_job_name }}.nomad
    mode: "0644"
  become: true

- name: Run n8n Nomad job
  ansible.builtin.command:
    cmd: "nomad job run /opt/nomad/jobs/{{ n8n_nomad_job_name }}.nomad"
  changed_when: true
  run_once: true
  become: true
