---
# Deregister the job from Nomad
- name: Unregister N8N job from Nomad
  ansible.builtin.command: >
    nomad job stop -purge n8n
  register: n8n_nomad_stop
  changed_when: "'purged' in n8n_nomad_stop.stdout"
  failed_when: false  # Job might not exist
  become: true

# Clean up the HCL file
- name: Remove n8n Nomad job spec file
  ansible.builtin.file:
    path: /etc/nomad/jobs/{{ n8n_nomad_job_name }}.nomad
    state: absent
