---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: Reload systemd

- name: Restart Nomad
  ansible.builtin.systemd:
    name: "{{ nomad_service }}"
    enabled: true
    state: restarted
  listen: Restart Nomad
  become: true

- name: Validate Nomad
  ansible.builtin.include_tasks: validate_server.yml
  when: nomad_server | default(false)
  listen: Validate Nomad

- name: Validate Nomad (client)
  ansible.builtin.include_tasks: validate_client.yml
  when: not nomad_server | default(true)
  listen: Validate Nomad
