---
- name: Restart nomad
  ansible.builtin.systemd:
    name: nomad
    state: restarted
    daemon_reload: true

- name: Restart consul
  ansible.builtin.systemd:
    name: consul
    state: restarted
