---
- name: Check for existing Nomad binary
  ansible.builtin.stat:
    path: "{{ nomad_bin_dir }}/nomad"
  register: nomad_bin

- name: Get installed Nomad version
  when: nomad_bin.stat.exists
  block:
    - name: Get installed Nomad version
      ansible.builtin.command:
        cmd: "{{ nomad_bin_dir }}/nomad version"
      register: installed_nomad_version
      changed_when: false
  rescue:
    - name: Fallback Failed to read Nomad version
      ansible.builtin.debug:
        msg: "Nomad binary exists but failed to report version"

- name: Report existing Nomad version
  ansible.builtin.debug:
    msg: >-
      Nomad is installed at {{ nomad_bin_dir }}/nomad,
      version: {{ installed_nomad_version.stdout | default('unknown') }}
  when: nomad_bin.stat.exists

- name: Report that Nomad is not installed
  ansible.builtin.debug:
    msg: "Nomad is not installed on this host"
  when: not nomad_bin.stat.exists

- name: Uninstall Nomad if disabled
  ansible.builtin.include_tasks: uninstall.yml
  when:
    - not nomad
    - nomad_bin.stat.exists

- name: Install, update, and validate Nomad when enabled
  when: nomad | default(false)
  become: true
  block:
    - name: Include install tasks
      ansible.builtin.include_tasks: install.yml
      when: not nomad_bin.stat.exists

    - name: Include update tasks
      ansible.builtin.include_tasks: update.yml
