---
- name: Set blank host_domains
  ansible.builtin.set_fact:
    host_domains: []

- name: Mark host as part of the orchestration domain
  ansible.builtin.set_fact:
    host_domains: "{{ (host_domains | default([])) + ['orchestration'] }}"
  when: >
    (
      orchestration.ansible    | default(false) | bool or
      orchestration.artifactory| default(false) | bool or
      orchestration.consul     == 'server'        or
      orchestration.nomad      == 'server'
    )
    and 'orchestration' not in (host_domains | default([]))

- name: Debug host_domains
  ansible.builtin.debug:
    var: host_domains
