---
postgres_build_image: true
postgres_dcs_config_type: "consul"
postgres_consul_host: host.docker.internal:8500

# no clusters by default
postgres_clusters: []

# where all data dirs live
postgres_data_root: /mnt/postgres

# defaults applied to every cluster unless overridden
postgres_cluster_defaults:
  # container images
  image: "docker-registry.service.consul:5050/library/postgres:15-alpine"
  patroni_image: "docker-registry.service.consul:5050/library/patroni:2.1.2"

  # replication
  replicas: 3

  # storage (host‐local by default)
  storage:
    type: host_volume
    size: "50Gi"
    # mount_path will be rendered per-cluster as "{{ postgres_data_root }}/{{ name }}"
    mount_path: ""

  # resource allocations
  resources:
    cpu: 500       # millicores
    memory: 1024   # MB

  # network
  network:
    # port: "{{ postgres_port }}" supersceded by postgres_port in group_vals/all/ports

  # Consul DCS settings
  consul:
    # prefix under which Patroni writes its keys
    dcs_path_prefix: "service"
    # suffix for the primary service name: "{{ name }}-primary"
    service_name_suffix: "-primary"

  # credentials
  credentials:
    username: postgres
    # you’ll still need to supply this via Vault or extra_vars
    password: "{{ postgresql_passwords.default }}"

  # placement hints
  placement:
    datacenters:
      - dc1
    constraints: []

  # arbitrary metadata tags
  metadata: {}
