---
- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ docker_apt_dependencies }}"
    state: present

- name: Create the /etc/apt/keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources list
  ansible.builtin.shell: |
    set -o pipefail
    echo "deb [arch={{ docker_arch | trim }} signed-by=/etc/apt/keyrings/docker.asc] \
    https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] | trim }} stable" | \
    sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash
  changed_when: false

- name: Update the apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  notify: Validate Docker

- name: Add current user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
