prod:
  hosts:
    devmacmbpm3p001:

staging:
  hosts:
    devmacmbpm3p001:

dev:
  hosts:
    devmacmbpm3p001:

devmacmbpm3p001_dev_vms:
  hosts:
    devubumlt0vm001:
      memory: 1
      storage: 8
      image: focal
