prod:
  hosts:
    devmacmbpm3p001:

staging:
  hosts:
    devmacmbpm3p001:

dev:
  hosts:
    devmacmbpm3p001:
      ansible_host: 192.168.1.214
  children:
    devmacmbpm3p001_dev_vms:

devmacmbpm3p001_dev_vms:
  hosts:
    devubumlt0vm001:
      memory: 1
      storage: 8
      image: noble
    devubumlt0vm002:
      memory: 1
      storage: 8
      image: noble
    devubumlt0vm003:
      memory: 1
      storage: 8
      image: noble
    devubumlt0vm004:
      memory: 4
      cores: 2
      storage: 40
      image: noble
    devubumlt0vm005:
      memory: 4
      cores: 2
      storage: 40
      image: noble
    devubumlt0vm006:
      memory: 4
      cores: 2
      storage: 40
      image: noble
    devubumlt0vm007:
      memory: 1
      storage: 8
      image: noble

multipass_vms:
  children:
    devmacmbpm3p001_dev_vms:

class_orchestration:
  hosts:
    devubumlt0vm001:
    devubumlt0vm002:
    devubumlt0vm003:

class_data:
  hosts:
    devubumlt0vm004:
    devubumlt0vm005:
    devubumlt0vm006:
    devubumlt0vm007:

domain_ai:
  hosts:
    devubumlt0vm004:
    devubumlt0vm005:
    devubumlt0vm006:

domain_infra:
  hosts:
    devubumlt0vm001:
    devubumlt0vm002:
    devubumlt0vm003:
    devubumlt0vm007:
