prod:
  hosts:
    devmacmbpm3p001:

staging:
  hosts:
    devmacmbpm3p001:

dev:
  hosts:
    devmacmbpm3p001:
      ansible_host: 192.168.1.214
  children:
    devmacmbpm3p001_dev_vms:

devmacmbpm3p001_dev_vms:
  hosts:
    devubumlt0vm001:
      memory: 1
      storage: 8
      image: focal
    devubumlt0vm002:
      cores: 2
      memory: 2
      storage: 8
      image: focal
    devubumlt0vm003:
      memory: 1
      storage: 8
      image: focal
    devubumlt0vm004:
      memory: 1
      storage: 8
      image: focal
    devubumlt0vm005:
      cores: 4
      memory: 2
      storage: 8
      image: focal
