---
- name: Create Consul service definition for PostgreSQL
  ansible.builtin.template:
    src: consul_postgresql_service.json.j2
    dest: "/etc/consul.d/postgresql.json"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Consul
    - Validate Postgres
