---
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add PostgreSQL APT signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    filename: "postgresql"

- name: Update apt cache after adding PostgreSQL repo
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    name: "{{ postgresql_apt_list }}"
    state: present
    update_cache: yes

- name: Install psycopg2-binary using pip module
  ansible.builtin.pip:
    name: psycopg2-binary
    executable: "{{ pip_executable }}"
    extra_args: --upgrade

- name: Ensure cluster is created and started
  ansible.builtin.command: >
    pg_createcluster {{ postgresql_version }} main --start
  args:
    creates: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
  become: true
