---
- name: Ensure users exist for this Postgres instance
  community.postgresql.postgresql_user:
    name: "{{ item.value.name }}"
    password: "{{ item.value.password }}"
    encrypted: true
    login_user: postgres
    login_password: "{{ postgresql_passwords.default }}"
    login_host: "127.0.0.1"
  loop: "{{ postgresql_users[datastores.postgres] | dict2items }}"

- name: Ensure databases exist for this Postgres instance
  community.postgresql.postgresql_db:
    name: "{{ item.value.name }}"
    owner: "{{ item.value.owner }}"
    login_user: postgres
    login_password: "{{ postgresql_passwords.default }}"
    login_host: "127.0.0.1"
  loop: "{{ postgresql_databases[datastores.postgres] | dict2items }}"
