---
- name: Derive postgresql_data_directory
  ansible.builtin.set_fact:
    postgresql_data_directory: "/var/lib/postgresql/{{ postgresql_version }}/main"

- name: Stop PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: stopped
  become: true
  ignore_errors: true

- name: Disable and unmask PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    enabled: false
    masked: false
  become: true
  ignore_errors: true

- name: Remove custom PostgreSQL systemd unit
  ansible.builtin.file:
    path: /etc/systemd/system/postgresql.service
    state: absent
  become: true

- name: Reload systemd after removing unit
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Remove PostgreSQL data directory
  ansible.builtin.file:
    path: "{{ postgresql_data_directory }}"
    state: absent
  become: true

- name: Uninstall PostgreSQL packages
  ansible.builtin.apt:
    name: "{{ postgresql_apt_list }}"
    state: absent
    purge: yes
  become: true

- name: Remove PostgreSQL APT repo
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: absent
    filename: "postgresql"
  become: true

- name: Remove PostgreSQL APT signing key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: absent
  become: true

- name: Remove psycopg2-binary from Python
  ansible.builtin.pip:
    name: psycopg2-binary
    executable: "{{ pip_executable }}"
    state: absent
  become: true
