---
- name: Configure postgresql.conf
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0644'
  notify:
    - Restart PostgreSQL
    - Validate Postgres

- name: Ensure PostgreSQL service is enabled and started
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Check if postgres user already has a password
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT passwd IS NOT NULL FROM pg_shadow WHERE usename='postgres';"
  args:
    executable: /bin/bash
    timeout: 10
  register: postgres_password_check
  changed_when: false
  failed_when: false

- name: Set postgres password via peer auth before forcing md5
  ansible.builtin.command: >
    sudo -u postgres psql -c "ALTER USER postgres PASSWORD '{{ postgresql_postgres_password }}';"
  args:
    executable: /bin/bash
  when:
    - postgresql_postgres_password is defined
    - postgres_password_check.stdout is defined
    - postgres_password_check.stdout.strip() == "f"

- name: Configure pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0640'
  notify:
    - Restart PostgreSQL
    - Validate Postgres
