---
- name: Check that PostgreSQL service is active
  ansible.builtin.service_facts:

- name: Fail if PostgreSQL service is not running
  ansible.builtin.fail:
    msg: "PostgreSQL service is not running!"
  when: "'postgresql' not in ansible_facts.services or ansible_facts.services['postgresql'].state != 'running'"

- name: Wait for PostgreSQL port to be open
  ansible.builtin.wait_for:
    port: "{{ postgresql_port }}"
    host: "{{ ansible_host }}"
    timeout: 30
    state: started

- name: Verify connection to PostgreSQL
  ansible.builtin.shell: |
    psql -h {{ ansible_host }} -p {{ postgresql_port }} -U postgres -c "SELECT 1;"
  register: postgres_connection
  failed_when: postgres_connection.rc != 0
  changed_when: false
  environment:
    PGPASSWORD: "{{ postgresql_postgres_password | default('') }}"
