---
n8n_version: "latest"
n8n_nomad_region: "global"

n8n_nomad_job_name: "n8n"
n8n_nomad_image: "docker.io/n8nio/n8n:{{ n8n_version }}"

n8n_data_path: "/opt/n8n"
n8n_env:
  GENERIC_TIMEZONE: "Australia/Sydney"
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "admin"
  N8N_BASIC_AUTH_PASSWORD: "{{ N8N_BASIC_AUTH_PASS }}"
  N8N_ENCRYPTION_KEY: "{{ N8N_EBC_KEY }}"
  N8N_HOST: "0.0.0.0"
  N8N_SECURE_COOKIE: "false"
