---
- name: Gather all hosts from the groups listed in 'nodes'
  ansible.builtin.set_fact:
    target_hosts: "{{ nodes | map('extract', groups) | flatten | unique }}"

- name: Ensure host_vars file exists for each host
  vars:
    host_vars_path: "{{ ansible_env.HOME }}/Jotunheim/ansible/host_vars"
  loop: "{{ target_hosts }}"
  ansible.builtin.file:
    path: "{{ host_vars_path }}/{{ item }}.yml"
    state: touch
    mode: '0644'
  changed_when: false
